content = open('ml_training.py').read()
content = content.replace('fraud_probability = 0.005', 'fraud_probability = 0.002')
content = content.replace('fraud_probability += 0.55', 'fraud_probability += 0.12')
content = content.replace('fraud_probability += 0.25', 'fraud_probability += 0.05')
content = content.replace('fraud_probability += 0.20', 'fraud_probability += 0.04')
content = content.replace('fraud_probability += 0.05\n\n        fraud_probability = min(fraud_probability, 0.98)', 'fraud_probability += 0.01\n\n        fraud_probability = min(fraud_probability, 0.95)')
content = content.replace('min(fraud_probability, 0.98)', 'min(fraud_probability, 0.95)')
open('ml_training.py', 'w').write(content)
print('Done! ml_training.py patched.')